name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL=DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWDlGMko1NVZEMDk3UlJTUVZQVktFVloiLCJ0ZW5hbnRfaWQiOiI5OWJlYTJlMTY3NmM1OGFlNmVhMzRkZWJiMTY4MDg1ZjhiNGYxOWIyYTc3M2E1MjVkNDg3NjdkZjNlM2MxODNkIiwiaW50ZXJuYWxfc2VjcmV0IjoiM2VjNjI3YjEtMjhhMC00ZWMzLWJiMWItZGVmZWEyMWViODk1In0.Of3k4DtST2K48SpzosD34d5oTsv4hNvIt7uCZTNfRpY"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"